### PR TITLE
releasetools: Use du -b

### PR DESCRIPTION
**Pull request by pablomh**
This allows building devices with dynamic partitions on file systems like ZFS that allow compression.

### CODE REVIEW

**Comment by thestinger** [comment]
Don't we need the toybox change for this to work? Isn't this just going to break from `-b` being missing?

**Comment by pablomh** [comment]
As far as I understand the issue here, it will use the `du` version in the build host and not the `toybox` one.

After applying only this change in my Ubuntu build host with compressed ZFS I went from:

```
[ 91% 1238/1347] Target system_ext fs image: out/target/product/sunfish/system_ext.img
FAILED: out/target/product/sunfish/system_ext.img
/bin/bash -c "(mkdir -p out/target/product/sunfish/system_ext ) && (mkdir -p out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates && rm -rf out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"system_ext_fs_type=ext4\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"system_ext_selinux_fc=out/target/product/sunfish/obj/ETC/file_contexts.bin_intermediates/file_contexts.bin\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"ext_mkuserimg=mkuserimg_mke2fs\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"fs_type=ext4\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"extfs_sparse_flag=-s\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"squashfs_sparse_flag=-s\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"f2fs_sparse_flag=-S\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"ext4_share_dup_blocks=true\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"avb_avbtool=avbtool\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"avb_system_hashtree_enable=true\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"avb_system_add_hashtree_footer_args=--prop com.android.build.system.fingerprint:\$(cat out/target/product/sunfish/build_fingerprint.txt) --prop com.android.build.system.os_version:11 --prop com.android.build.system.security_patch:2020-11-05\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"avb_system_other_hashtree_enable=true\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"avb_system_other_add_hashtree_footer_args=\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"avb_vendor_hashtree_enable=true\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"avb_vendor_add_hashtree_footer_args=--prop com.android.build.vendor.fingerprint:\$(cat out/target/product/sunfish/build_fingerprint.txt) --prop com.android.build.vendor.os_version:11 --prop com.android.build.vendor.security_patch:2020-11-05\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"avb_product_hashtree_enable=true\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"avb_product_add_hashtree_footer_args=--prop com.android.build.product.fingerprint:\$(cat out/target/product/sunfish/build_fingerprint.txt) --prop com.android.build.product.os_version:11 --prop com.android.build.product.security_patch:2020-11-05\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"avb_system_ext_hashtree_enable=true\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"avb_system_ext_add_hashtree_footer_args=--prop com.android.build.system_ext.fingerprint:\$(cat out/target/product/sunfish/build_fingerprint.txt) --prop com.android.build.system_ext.os_version:11 --prop com.android.build.system_ext.security_patch:2020-11-05\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"avb_odm_hashtree_enable=true\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"avb_odm_add_hashtree_footer_args=--prop com.android.build.odm.fingerprint:\$(cat out/target/product/sunfish/build_fingerprint.txt) --prop com.android.build.odm.os_version:11\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"recovery_as_boot=true\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"root_dir=out/target/product/sunfish/root\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"use_dynamic_partition_size=true\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (echo \"skip_fsck=true\" >>  out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt ) && (PATH=out/host/linux-x86/bin/:system/extras/ext4_utils/:\$PATH out/host/linux-x86/bin/build_image out/target/product/sunfish/system_ext out/target/product/sunfish/obj/PACKAGING/system_ext_intermediates/system_ext_image_info.txt out/target/product/sunfish/system_ext.img out/target/product/sunfish/system ) && (true )"
2020-11-12 09:39:02 - build_image.py - ERROR   : Failed to build out/target/product/sunfish/system_ext.img from out/target/product/sunfish/system_ext
Out of space? Out of inodes? The tree size of out/target/product/sunfish/system_ext is 92485632 bytes (88 MB), with reserved space of 0 bytes (0 MB).
The max image size for filesystem files is 109264896 bytes (104 MB), out of a total partition size of 109264896 bytes (104 MB).
Traceback (most recent call last):
  File "/repos/GOS/out/host/linux-x86/bin/build_image/internal/stdlib/runpy.py", line 174, in _run_module_as_main
  File "/repos/GOS/out/host/linux-x86/bin/build_image/internal/stdlib/runpy.py", line 72, in _run_code
  File "/repos/GOS/out/host/linux-x86/bin/build_image/__main__.py", line 12, in <module>
  File "/repos/GOS/out/host/linux-x86/bin/build_image/internal/stdlib/runpy.py", line 174, in _run_module_as_main
  File "/repos/GOS/out/host/linux-x86/bin/build_image/internal/stdlib/runpy.py", line 72, in _run_code
  File "/repos/GOS/out/host/linux-x86/bin/build_image/build_image.py", line 815, in <module>
  File "/repos/GOS/out/host/linux-x86/bin/build_image/build_image.py", line 807, in main
  File "/repos/GOS/out/host/linux-x86/bin/build_image/build_image.py", line 434, in BuildImage
  File "/repos/GOS/out/host/linux-x86/bin/build_image/build_image.py", line 345, in BuildImageMkfs
  File "/repos/GOS/out/host/linux-x86/bin/build_image/common.py", line 281, in RunAndCheckOutput
common.ExternalError: Failed to run command '['mkuserimg_mke2fs', '-s', 'out/target/product/sunfish/system_ext', 'out/target/product/sunfish/system_ext.img', 'ext4', 'system_ext', '109264896', '-j', '0', '-D', 'out/target/product/sunfish/system', '-L', 'system_ext', '-i', '82', '-M', '0', '-c', '--inode_size', '256', 'out/target/product/sunfish/obj/ETC/file_contexts.bin_intermediates/file_contexts.bin']' (exit code 4):
09:39:01 mkuserimg_mke2fs.py INFO: Env: {'MKE2FS_CONFIG': '/repos/GOS/out/soong/.temp/tmpRcw8T1'}
09:39:01 mkuserimg_mke2fs.py INFO: Running: mke2fs -O ^has_journal -L system_ext -N 82 -I 256 -M /system_ext -m 0 -E android_sparse -t ext4 -b 4096 out/target/product/sunfish/system_ext.img 26676
09:39:01 mkuserimg_mke2fs.py INFO: Env: {}
09:39:01 mkuserimg_mke2fs.py INFO: Running: e2fsdroid -p out/target/product/sunfish/system -s -S out/target/product/sunfish/obj/ETC/file_contexts.bin_intermediates/file_contexts.bin -f out/target/product/sunfish/system_ext -a /system_ext out/target/product/sunfish/system_ext.img
09:39:02 mkuserimg_mke2fs.py ERROR: Failed to run e2fsdroid_cmd: __populate_fs: Could not allocate block in ext2 filesystem while writing file "StorageManager.apk"
e2fsdroid: Could not allocate block in ext2 filesystem while populating file system
```

For both system_ext and product, to:

```
[ 98% 1034/1047] Target system_ext fs image: out/target/product/sunfish/system_ext.img
. . 
[ 99% 1042/1047] Target product fs image: out/target/product/sunfish/product.img
. . .
++++ system_ext  ++++


2020-11-12 09:41:50 - add_img_to_target_files.py - INFO    : creating system_ext.img...
2020-11-12 09:41:50 - build_image.py - INFO    : The tree size of /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/SYSTEM_EXT is 156 MB.
2020-11-12 09:41:50 - build_image.py - INFO    : First Pass based on estimates of 172 MB and 82 inodes.
2020-11-12 09:41:50 - common.py - INFO    :   Running: "mkuserimg_mke2fs -s /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/SYSTEM_EXT /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/IMAGES/system_ext.img ext4 system_ext 180842496 -j 0 -T 1230768000 -C /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/META/system_ext_filesystem_config.txt -B /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/IMAGES/system_ext.map -L system_ext -i 82 -M 0 -U b5f6c35f-78d4-54b5-8504-aee39f515cb4 -S 36b20abe-b26e-52ce-a6fc-05f9b9986e8f -c --inode_size 256 /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/META/file_contexts.bin"
2020-11-12 09:41:51 - common.py - INFO    : 09:41:50 mkuserimg_mke2fs.py INFO: Env: {'E2FSPROGS_FAKE_TIME': '1230768000', 'MKE2FS_CONFIG': '/repos/GOS/out/soong/.temp/tmpOtPsLY'}
09:41:50 mkuserimg_mke2fs.py INFO: Running: mke2fs -O ^has_journal -L system_ext -N 82 -I 256 -M /system_ext -m 0 -U b5f6c35f-78d4-54b5-8504-aee39f515cb4 -E android_sparse,hash_seed=36b20abe-b26e-52ce-a6fc-05f9b9986e8f -t ext4 -b 4096 /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/IMAGES/system_ext.img 44151
09:41:50 mkuserimg_mke2fs.py INFO: Env: {'E2FSPROGS_FAKE_TIME': '1230768000'}
09:41:50 mkuserimg_mke2fs.py INFO: Running: e2fsdroid -T 1230768000 -C /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/META/system_ext_filesystem_config.txt -B /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/IMAGES/system_ext.map -s -S /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/META/file_contexts.bin -f /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/SYSTEM_EXT -a /system_ext /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/IMAGES/system_ext.img
mke2fs 1.45.4 (23-Sep-2019)
Creating filesystem with 44151 4k blocks and 96 inodes
Filesystem UUID: b5f6c35f-78d4-54b5-8504-aee39f515cb4
Superblock backups stored on blocks:
        32768

Allocating group tables: done
Writing inode tables: done
Writing superblocks and filesystem accounting information: done


loaded 70 fs_config entries
Created filesystem with 80/96 inodes and 39073/44151 blocks
2020-11-12 09:41:51 - common.py - INFO    :   Running: "simg2img /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/IMAGES/system_ext.img /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/IMAGES/unsparse_system_ext.img"
2020-11-12 09:41:51 - common.py - INFO    :
2020-11-12 09:41:51 - common.py - INFO    :   Running: "e2fsck -f -n /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/IMAGES/unsparse_system_ext.img"
2020-11-12 09:41:51 - common.py - INFO    : e2fsck 1.45.4 (23-Sep-2019)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
system_ext: 80/96 files (2.5% non-contiguous), 39073/44151 blocks
2020-11-12 09:41:51 - common.py - INFO    :   Running: "simg2img /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/IMAGES/system_ext.img /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/IMAGES/unsparse_system_ext.img"
2020-11-12 09:41:51 - common.py - INFO    :
2020-11-12 09:41:51 - build_image.py - INFO    : Allocating 81 Inodes for /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/IMAGES/system_ext.img.
2020-11-12 09:41:51 - common.py - INFO    :   Running: "avbtool add_hashtree_footer --partition_size 160526336 --calc_max_image_size --prop com.android.build.system_ext.fingerprint:Android/aosp_sunfish/sunfish:11/RP1A.201105.002/2020.11.11.09:user/test-keys --prop com.android.build.system_ext.os_version:11 --prop com.android.build.system_ext.security_patch:2020-11-05"
2020-11-12 09:41:51 - common.py - INFO    :   Running: "avbtool add_hashtree_footer --partition_size 163180544 --calc_max_image_size --prop com.android.build.system_ext.fingerprint:Android/aosp_sunfish/sunfish:11/RP1A.201105.002/2020.11.11.09:user/test-keys --prop com.android.build.system_ext.os_version:11 --prop com.android.build.system_ext.security_patch:2020-11-05"
2020-11-12 09:41:51 - common.py - INFO    :   Running: "avbtool add_hashtree_footer --partition_size 163184640 --calc_max_image_size --prop com.android.build.system_ext.fingerprint:Android/aosp_sunfish/sunfish:11/RP1A.201105.002/2020.11.11.09:user/test-keys --prop com.android.build.system_ext.os_version:11 --prop com.android.build.system_ext.security_patch:2020-11-05"
2020-11-12 09:41:51 - common.py - INFO    :   Running: "avbtool add_hashtree_footer --partition_size 163192832 --calc_max_image_size --prop com.android.build.system_ext.fingerprint:Android/aosp_sunfish/sunfish:11/RP1A.201105.002/2020.11.11.09:user/test-keys --prop com.android.build.system_ext.os_version:11 --prop com.android.build.system_ext.security_patch:2020-11-05"
2020-11-12 09:41:52 - common.py - INFO    :   Running: "avbtool add_hashtree_footer --partition_size 163184640 --calc_max_image_size --prop com.android.build.system_ext.fingerprint:Android/aosp_sunfish/sunfish:11/RP1A.201105.002/2020.11.11.09:user/test-keys --prop com.android.build.system_ext.os_version:11 --prop com.android.build.system_ext.security_patch:2020-11-05"
2020-11-12 09:41:52 - common.py - INFO    :   Running: "avbtool add_hashtree_footer --partition_size 163188736 --calc_max_image_size --prop com.android.build.system_ext.fingerprint:Android/aosp_sunfish/sunfish:11/RP1A.201105.002/2020.11.11.09:user/test-keys --prop com.android.build.system_ext.os_version:11 --prop com.android.build.system_ext.security_patch:2020-11-05"
2020-11-12 09:41:52 - verity_utils.py - INFO    : CalculateMinPartitionSize(160526336): partition_size 163188736.
2020-11-12 09:41:52 - build_image.py - INFO    : Allocating 155 MB for /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/IMAGES/system_ext.img.
2020-11-12 09:41:52 - common.py - INFO    :   Running: "avbtool add_hashtree_footer --partition_size 163188736 --calc_max_image_size --prop com.android.build.system_ext.fingerprint:Android/aosp_sunfish/sunfish:11/RP1A.201105.002/2020.11.11.09:user/test-keys --prop com.android.build.system_ext.os_version:11 --prop com.android.build.system_ext.security_patch:2020-11-05"
2020-11-12 09:41:52 - common.py - INFO    :   Running: "mkuserimg_mke2fs -s /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/SYSTEM_EXT /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/IMAGES/system_ext.img ext4 system_ext 160526336 -j 0 -T 1230768000 -C /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/META/system_ext_filesystem_config.txt -B /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/IMAGES/system_ext.map -L system_ext -i 81 -M 0 -U b5f6c35f-78d4-54b5-8504-aee39f515cb4 -S 36b20abe-b26e-52ce-a6fc-05f9b9986e8f -c --inode_size 256 /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/META/file_contexts.bin"
2020-11-12 09:41:53 - common.py - INFO    : 09:41:52 mkuserimg_mke2fs.py INFO: Env: {'E2FSPROGS_FAKE_TIME': '1230768000', 'MKE2FS_CONFIG': '/repos/GOS/out/soong/.temp/tmpwJGcAE'}
09:41:52 mkuserimg_mke2fs.py INFO: Running: mke2fs -O ^has_journal -L system_ext -N 81 -I 256 -M /system_ext -m 0 -U b5f6c35f-78d4-54b5-8504-aee39f515cb4 -E android_sparse,hash_seed=36b20abe-b26e-52ce-a6fc-05f9b9986e8f -t ext4 -b 4096 /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/IMAGES/system_ext.img 39191
09:41:52 mkuserimg_mke2fs.py INFO: Env: {'E2FSPROGS_FAKE_TIME': '1230768000'}
09:41:52 mkuserimg_mke2fs.py INFO: Running: e2fsdroid -T 1230768000 -C /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/META/system_ext_filesystem_config.txt -B /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/IMAGES/system_ext.map -s -S /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/META/file_contexts.bin -f /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/SYSTEM_EXT -a /system_ext /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/IMAGES/system_ext.img
mke2fs 1.45.4 (23-Sep-2019)
Creating filesystem with 39191 4k blocks and 96 inodes
Filesystem UUID: b5f6c35f-78d4-54b5-8504-aee39f515cb4
Superblock backups stored on blocks:
        32768

Allocating group tables: done
Writing inode tables: done
Writing superblocks and filesystem accounting information: done


loaded 70 fs_config entries
Created filesystem with 80/96 inodes and 39073/39191 blocks
2020-11-12 09:41:53 - common.py - INFO    :   Running: "simg2img /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/IMAGES/system_ext.img /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/IMAGES/unsparse_system_ext.img"
2020-11-12 09:41:53 - common.py - INFO    :
2020-11-12 09:41:53 - common.py - INFO    :   Running: "e2fsck -f -n /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/IMAGES/unsparse_system_ext.img"
2020-11-12 09:41:53 - common.py - INFO    : e2fsck 1.45.4 (23-Sep-2019)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
system_ext: 80/96 files (2.5% non-contiguous), 39073/39191 blocks
2020-11-12 09:41:53 - common.py - INFO    :   Running: "avbtool add_hashtree_footer --partition_size 163188736 --partition_name system_ext --image /repos/GOS/out/target/product/sunfish/obj/PACKAGING/target_files_intermediates/aosp_sunfish-target_files-2020.11.11.09/IMAGES/system_ext.img --salt f3648f0cb4e401d5f4bfaa16a092fb45be5527586d75f075a561457454cdf1a0 --prop com.android.build.system_ext.fingerprint:Android/aosp_sunfish/sunfish:11/RP1A.201105.002/2020.11.11.09:user/test-keys --prop com.android.build.system_ext.os_version:11 --prop com.android.build.system_ext.security_patch:2020-11-05"
2020-11-12 09:41:54 - add_img_to_target_files.py - INFO    :
. . .
```

**Comment by thestinger** [comment]
I cherry-picked the AOSP commit. Thanks!

**Comment by thestinger** [comment]
Our toybox was updated for another reason so it has the necessary switch.

**Pull request closed without merging**
